version: '3'

services:

    ### Workspace Utilities ##################################
    workspace:
        platform: linux/x86_64
        image: registry.cn-hangzhou.aliyuncs.com/mn/laravel-workspace:dev-8.0.0
        volumes:
            - ./:/var/www
        logging:
            options:
                max-file: "5"
                max-size: "10m"

    ### PHP-FPM ##############################################
    php-fpm:
        platform: linux/x86_64
        image: registry.cn-hangzhou.aliyuncs.com/mn/mhd_glenmorangie_cask_mp_backend_php-fpm:0.0.1
        volumes:
            - ./docker/php-fpm/php8.0.ini:/usr/local/etc/php/php.ini
            - ./:/var/www:cached
        expose:
            -  9000
        logging:
            options:
                max-file: "5"
                max-size: "10m"

    ### PHP Worker ############################################
    php-worker:
        platform: linux/x86_64
        image: registry.cn-hangzhou.aliyuncs.com/mn/laravel-php_worker:dev-8.0.0
        volumes:
            - ./:/var/www:cached
            - ./docker/php-worker/supervisord.d:/etc/supervisord.d
        depends_on:
            - php-fpm
        links:
            - php-fpm
        logging:
            options:
                max-file: "5"
                max-size: "10m"

    ### NGINX Server #########################################
    nginx:
        build:
            context: ./docker/nginx
            args:
                - PHP_UPSTREAM_CONTAINER=php-fpm
                - PHP_UPSTREAM_PORT=9000
        volumes:
            - ./:/var/www:cached
            - ./docker/docker-runtime/nginx/log:/var/log/nginx
            - ./docker/nginx/local/sites:/etc/nginx/sites-available
        ports:
            - "8000:80"
        expose:
            - "8000"
        depends_on:
            - php-fpm
        links:
            - php-fpm

    ### MySQL ################################################
    mysql:
        platform: linux/x86_64
        build:
            context: ./docker/mysql
            args:
                - MYSQL_VERSION=5.7
        environment:
            - MYSQL_USERNAME=root
            - MYSQL_ROOT_PASSWORD=123456
            - TZ=Asia/Shanghai
        volumes:
            - ./docker/docker-runtime/mysql:/var/lib/mysql
            - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "33060:3306"

    ### Redis ################################################
    redis:
        image: redis:latest
        volumes:
            - ./docker/docker-runtime/redis:/data
        ports:
            - "6379:6379"
        logging:
            options:
                max-file: "5"
                max-size: "10m"
    ### RabbitMQ #############################################
    rabbitmq:
        build:
            context: ./docker/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
            - "15671:15671"
            - "15674:15674"
        privileged: true
        hostname: laradock-rabbitmq
        volumes:
            - ./docker/docker-runtime/rabbitmq:/var/lib/rabbitmq
            - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./docker/rabbitmq/management_agent.disable_metrics_collector.conf:/etc/rabbitmq/conf.d/management_agent.disable_metrics_collector.conf
        depends_on:
            - php-fpm
        logging:
            options:
                max-file: "5"
                max-size: "10m"
